# THINGs Dataset Configuration
dataset:
  name: "ds004192"
  source: "https://github.com/OpenNeuroDatasets/ds004192"
  subjects: ["01", "02", "03"]
  sessions: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]

# ROI Definitions (MNI coordinates will be defined in preprocess.py)
rois:
  dorsal:
    - "intraparietal_sulcus"
    - "superior_parietal_lobule" 
    - "mt_v5"
  ventral:
    - "fusiform_gyrus"
    - "lateral_occipital_complex"
    - "inferior_temporal_cortex"

# Analysis Parameters
analysis:
  classifier: "svm"
  cv_folds: 5
  n_permutations: 1000
  smoothing_fwhm: 3.0
